name: eslint-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: cd frontend
      - run: npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml .